version: '2'
services:
  nginx:
    image: nginx:latest
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /etc/worldhistorymap.io/certs:/certs
      - /data/worldhistorymap.io/tiles:/tileserver/tiles
      - /data/worldhistorymap.io/legends:/tileserver/legends
    ports:
      - 443:443
    restart: always

  historymap-react1:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:react
    restart: always

  historymap-react2:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:react
    restart: always

  historymap-react3:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:react
    restart: always

