version: '2'
services:
  nginx:
    image: nginx:latest
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /etc/worldhistorymap.io/certs:/certs
    ports:
      - 443:443
    restart: always

  react1:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:react
    restart: always

  react2:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:react
    restart: always

  react3:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:react
    restart: always

  tileserver1:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:tileserver
    restart: always
    volumes:
      - /data/worldhistorymap.io/tiles:/tiles/

  tileserver2:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:tileserver
    restart: always
    volumes:
      - /data/worldhistorymap.io/tiles:/tiles/

  tileserver3:
    depends_on:
      - nginx
    image: worldhistorymap/historymap:tileserver
    restart: always
    volumes:
      - /data/worldhistorymap.io/tiles:/tiles/

