version: '3'
services:
  nginx:
    image: nginx:latest
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/worldhistorymap.io:/etc/letsencrypt
    ports:
      - 443:443
  tileserver1:
    build: ./tileserver/
    tty: true
    volumes:
      - /data/www/worldhistorymap.io/tiles:/tiles
      - /data/www/worldhistorymap.io/legends:/legends
    expose:
      - "80" 
  tileserver2:
    build: ./tileserver/
    tty: true
    volumes:
      - /data/www/worldhistorymap.io/tiles:/tiles
      - /data/www/worldhistorymap.io/legends:/legends
    expose:
      - "80" 
  tileserver3:
    build: ./tileserver/
    tty: true
    volumes:
      - /data/www/worldhistorymap.io/tiles:/tiles
      - /data/www/worldhistorymap.io/legends:/legends
    expose:
      - "80" 
